### ISSUE TITLE
Research and Validate Grammar for HOCON

### ISSUE THREAD

**Issue by Jcabza008** [ConfigMate/configmate#28]
## Description
As HOCON is a recognized config file language but lacks widely available ANTLR grammars, it's crucial to research, draft, and validate a grammar for it. There's an indication that HOCON is highly similar to JSON5, but the exact similarities need to be clarified to confidently parse HOCON files.

## Completion Criteria
- [x] Research and document the similarities and differences between HOCON and JSON5.
- [x] Draft a preliminary ANTLR grammar for HOCON based on the findings.
- [x] Validate the drafted grammar by testing it against various HOCON file examples.
- [x] Review the validation results and refine the grammar as necessary.

## References
- [HOCON Specification](https://github.com/lightbend/config/blob/master/HOCON.md)
- [JSON5 Official Website](https://json5.org/)

**Comment by javier-arango** [comment]
Closed by #57
